// <auto-generated />
namespace CompleteWebSite.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MapItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MapItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201507052128401_MapItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
