// <auto-generated />
namespace CompleteWebSite.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UploadedBy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UploadedBy));
        
        string IMigrationMetadata.Id
        {
            get { return "201507052215076_UploadedBy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
